version: '2'
  
services:
    # sqlscript:
    #     build:
    #         context: database/
    #         dockerfile: Dockerfile
    sli.do:
        container_name: 'sli.do.web'
        build:
            context: sli.do/
            dockerfile: Dockerfile
        ports:
          - "3000:5000"
    sli.do.server:
        container_name: 'sli-do-server'
        build:
            context: sli.do.server/
            dockerfile: Dockerfile
        ports:
          - "1337:1337"
        links:
            - mysqldb
    mysqldb:
        image: mysql
        container_name: 'mysql-localhost'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123
            - MYSQL_DATABASE=sli.do
            - MYSQL_USER=sli
            - MYSQL_PASSWORD=123
        ports:
            - "3306:3306"
        volumes:
        #   - "./data/db/mysql:/var/lib/mysql"
          - "./database:/docker-entrypoint-initdb.d"
        # volumes_from:
        #   - sqlscript