export const APP_LOAD_CONTENT = 'APP_LOAD_CONTENT';
export const APP_JOIN_EVENT = 'APP_JOIN_EVENT';
export const APP_USER_LOADED = 'APP_USER_LOADED';


/**
 * AUDIENCE ACTION
 */
export const AUDIENCE_ADD_COMMENT = 'AUDIENCE_ADD_COMMENT';
/**
 * END OF AUDIENCE ACTION
 */