export const APP_LOAD_CONTENT = 'APP_LOAD_CONTENT';
export const APP_EVENT_BY_CODE_SEARCHED = 'APP_EVENT_BY_CODE_SEARCHED';
export const APP_USER_LOADED = 'APP_USER_LOADED';


/**
 * AUDIENCE ACTION
 */
export const AUDIENCE_ADD_COMMENT = 'AUDIENCE_ADD_COMMENT';
export const AUDIENCE_EVENT_DETAIL_LOADED = 'AUDIENCE_EVENT_DETAIL_LOADED';
export const AUDIENCE_PUB_ON_NEW_COMMENT_ADDED = 'AUDIENCE_PUB_ON_NEW_COMMENT_ADDED';
/**
 * END OF AUDIENCE ACTION
 */

 /**
  * DASHBOARD ACTION
  */
export const DASHBOARD_ADD_NEW_EVENT = 'DASHBOARD_ADD_NEW_EVENT';
export const DASHBOARD_EVENTS_LOADED = 'DASHBOARD_EVENTS_LOADED';
export const DASHBOARD_EVENT_DETAIL_LOADED = 'DASHBOARD_EVENT_DETAIL_LOADED';
export const DASHBOARD_PUB_ON_NEW_COMMENT_ADDED = 'DASHBOARD_PUB_ON_NEW_COMMENT_ADDED';
/**
 * END OF DASHBOARD ACTION
 */